name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm ci --legacy-peer-deps

      # Run Nx tasks (lint, test, build)
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build

      # Install and start Nginx
      - name: Install and start Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx

      # Run ZAP security scan
      - name: ZAP Scan
        uses: ./
        id: action-full-scan
        with:
          target: 'http://localhost'
          allow_issue_writing: false

      # Optional: Record tasks to Nx Cloud (uncomment if needed)
      # - run: npx nx-cloud record -- echo "Nx Cloud Recording"
