name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules and set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm ci --legacy-peer-deps

      # Set SHAs for Nx
      - uses: nrwl/nx-set-shas@v4

      # Run Nx affected tasks (lint, build)
      - run: npx nx affected -t lint build

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
            
